name: Release

on:
  release:
    types: [published]

  # Enable manual run
  workflow_dispatch:

jobs:
  build_dist_files:
    name: Build distribution files
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install build tool
        run: python -m pip install build

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel .

      - name: Upload dist files
        uses: actions/upload-artifact@v2
        with:
          name: dist_files
          path: dist/*

  upload_release_assets:
    name:  Upload Release Assets
    needs: [build_dist_files]
    runs-on: ubuntu-20.04

    steps:
      - name: Download dist files
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: dist_files
          path: ~/downloads

      - name: List downloaded artifacts
        run: ls -la ~/downloads

      - name: Upload to release
        uses: shogo82148/actions-upload-release-asset@v1.2.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.download_artifact.outputs.download-path }}/*.whl

  pypi_publish:
    name:  PyPI Publish
    needs: [upload_release_assets]
    runs-on: ubuntu-20.04

    steps:
      - name: Download dist files
        uses: actions/download-artifact@v2
        with:
          name: dist_files
          path: downloads/

      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: downloads/
          # repository_url: https://test.pypi.org/legacy/
          # verbose: true
